### ISSUE TITLE
/credit/payroll_income/get: Invalid type for variable 'owners'

### ISSUE THREAD

**Issue by MariaMozgunova** [plaid/plaid-python#471] opened 2023-06-14 08:59 UTC
Hello,

Thank you for your great work at parsing complex data from Plaid API!

We are experiencing issues with `/credit/payroll_income/get` endpoint. The error message is the following:

```
plaid.exceptions.ApiTypeError: Invalid type for variable 'owners'. Required value type is list and passed type was NoneType at ['received_data']['bank_income'][0]['items'][0]['bank_income_accounts'][0]['owners']
```

Looks like you do not expect the `owners` variable to be `None`

Please, note that we are using `plaid-python` library version `12.0.0`. I tried to upgrade but no updates were found so it seems to be the latest available version.

We have experienced parsing issues multiple times now. Do you think you can look into how to decrease the probability of facing parsing errors?

Best regards,
Maria

**Comment by phoenixy1** [comment] 2023-06-14 23:26
Thanks for the report! I've flagged the team that owns this and they said they'll work on a fix soon, hopefully it will be in time for next week's client library release, and if not it should be ready for the July release. 

The latest client library version for python is actually version 14 -- i'm not sure why it isn't showing up for you but it definitely exists: https://pypi.org/project/plaid-python/ Updating to the latest client library version should minimize the number of parsing errors you're hitting, as if you're stuck on 12 you aren't getting any new bug fixes.

Beyond that, it really helps us if you can report any issues here on GitHub -- the issues tend to be fairly simple (generally the root cause is that the API implementation diverges from the API spec in edge cases) and we are usually able to fix them fairly quickly after they've been reported.

**Comment by phoenixy1** [comment] 2023-06-16 20:41
@MariaMozgunova The team let me know that this issue should now be fixed; let me know if you're still seeing problems here.

**Comment by phoenixy1** [comment] 2023-06-16 20:42
(closing the issue, will re-open if necessary)

**Closed by phoenixy1** 2023-06-16 20:42 UTC

**Comment by phoenixy1** [comment] 2023-06-16 20:43
@MariaMozgunova one clarification from the team -- this is fixed in code but the fix has not yet been deployed. Monday is a federal holiday so we plan to deploy the fix on friday
